// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Group defines model for Group.
type Group struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// GroupsList defines model for GroupsList.
type GroupsList = []Group

// IGroup defines model for IGroup.
type IGroup struct {
	Name string `json:"name"`
}

// ILogin defines model for ILogin.
type ILogin struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Id defines model for Id.
type Id struct {
	Id int `json:"id"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = ILogin

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = IGroup

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = IGroup

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/auth/login)
	Login(c *gin.Context)

	// (GET /api/groups)
	GetMyGroups(c *gin.Context)

	// (POST /api/groups)
	CreateGroup(c *gin.Context)

	// (DELETE /api/groups/{id})
	DeleteGroup(c *gin.Context, id int)

	// (GET /api/groups/{id})
	GetGroup(c *gin.Context, id int)

	// (PUT /api/groups/{id})
	UpdateGroup(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// GetMyGroups operation middleware
func (siw *ServerInterfaceWrapper) GetMyGroups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyGroups(c)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateGroup(c)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGroup(c, id)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGroup(c, id)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateGroup(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/auth/login", wrapper.Login)
	router.GET(options.BaseURL+"/api/groups", wrapper.GetMyGroups)
	router.POST(options.BaseURL+"/api/groups", wrapper.CreateGroup)
	router.DELETE(options.BaseURL+"/api/groups/:id", wrapper.DeleteGroup)
	router.GET(options.BaseURL+"/api/groups/:id", wrapper.GetGroup)
	router.PUT(options.BaseURL+"/api/groups/:id", wrapper.UpdateGroup)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fbfb9MwEP5XLMNjWLofL7Taw1bQmBjaROGpVMhLrom3xDb2BVZV+d/R2VnTNuk2wfaAxNPm+O7z3fd9",
	"PnfJE10arUCh48Mlt+CMVg784lSkn+FHBQ5plYJLrDQoteJD2mM2bDJtmVSmQl7XEXdJDqXw+WdWV4b+",
	"EUVxOefD6ZK/tjDnQ/4qbo+Nm4z4PMTX0SNhKa9ndRTQ3YUM1UmE0h/6UOr9ARwXBviQC2vFgtbnq1KN",
	"1QYsysCAEiXQ3ybeoZUq821S79JCyofTEDVboerrG0jQw17oTKourBHO/dI27YGOeOXAPu3cVWTUIvaW",
	"kXZLkOuHS4WQge0cIPvwSGNIKitxMSFeA54D56RWY61vpS+d+uZJWEYNkfdR32XKWxGM/AgLXhOwVHPd",
	"9dqXXDomHcMcGNwZUA4YWpHcSpUxYcw3RWgSC4J7HwJ4xH+CdQFgf2+wNyAmtAEljORDfug/EXGY+wZi",
	"YWQsKszjYiWaDt4i3gTVQkTyoGkgChye6nRBQYlWCMrHC2MKmfiM+MZpjxUs+JhBG8PUm0KgraCONu/m",
	"wWDQJWpSJQk4xyOeg0jB+sgJ4JtWlq2EoAdb6eSSvARfJtyJ0hSboh2L62T/4HDEPiCaS1UsRmxCVoAR",
	"m4gSJhLh+ELcjdiVwPw45lHHwNTY0WCwi4dVi/Ha7KEcFJkjR55UmPMZffF6ZX4GEFoGPVKdAX5ahDnB",
	"+/l7FtXWJpFvsF+U9TaammiM9ZtsbEEg+LCXslozDJ9steej6kGW/s4fa8TeDyn/7myNp+msnm16KF7K",
	"tA4XpACEriLv/PdWkQ2CjnbfxT9piFLediHHWs0LmeAem+gS2FirVNIWmwtZQLqLiF1XY0cv/6TYRlhR",
	"AvqRN20eHxrt7dPjn5xNo0drfXRewlnETdVD3FeT/r+ZL3wz27TtK+BRWCmUyKAEhezk6ty1IjeH1NF2",
	"Hr0boLChZiuLNuk35e8BAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
